**TASK 1**
*Create a 1D array of numbers from 0 to 9*

In [9]:
# A One dimension array of numbers 0-9
#import numpy
import numpy as np
Array = np.arange(10)
print(Array)

[0 1 2 3 4 5 6 7 8 9]


***TASK 2***

*Create a 3×3 NumPy array of all Boolean value Trues*

In [10]:
#using the np.ones function
Bool = np.ones((3,3), dtype=bool)
print(Bool)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


***Task 3***
*Extract all odd numbers from array of 1-10*

In [11]:
#using the np.array  function

Odds = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Oddss = Odds[Odds % 2 == 1]
print(Oddss)

[1 3 5 7 9]


***TASK 4***

*Replace all odd numbers in an array of 1-10 with the value -1*

In [12]:
#Given that 
Odds = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#To replace the values of odds with -1 we have
Ods= Odds[Odds % 2 == 1] = -1
print(Ods)

-1


***OR***

In [13]:
#use the np.where function
Oddds = np.where(Odds % 2 == 1, -1, Odds)
print(Oddds)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


***Task 5***

*Convert a 1D array to a 2D array with 2 rows*

In [14]:
#To reshape an array, we use the reshape function
Arrange = np.arange(10)
print(Arrange)
#therefore, to reshape
Narrange = Arrange.reshape (2,5)
print(Narrange)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


***Task 6***

*Create two arrays a and b, stack these two arrays vertically use the np.dot and
np.sum to calculate totals*

In [42]:
a = np.arange(20,30).reshape(2,5)

b = np.arange(30,40).reshape(2,5)
#To print vertically, we use the concatenate function
c= np.concatenate([a, b], axis=0)
print(c)

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [47]:
#using the np.dot and np.sum to calculate totals, we have
a = np.arange(1,10).reshape(3,3)

b = np.arange(10, 19).reshape(3,3)
print("a = " , a )
print ("b = ", b )
#using the np.dot function to multiply
d = np.dot(a,b)
print("d = ", d)
sum = np.sum(d)
print("sum =", sum )

a =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
b =  [[10 11 12]
 [13 14 15]
 [16 17 18]]
d =  [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
sum = 1944
